spring.application.name=ai-mentor
//Postgress
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=6770

//Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

//Jwt
jwt.secret=7f4c9a2e6d8b1f3c5a7e9d2b4c6f8a1e3d5b7c9f2a4e6d8c1b3f5a7e9d2c4b6
jwt.expiration=86400000